java -cp /n/rinn_data1/user-supported/bin/gsea2-2.07.jar -Xmx5000m xtools.gsea.GseaPreranked -gmx gseaftp.broadinstitute.org://pub/gsea/gene_sets/c2.all.v3.0.symbols.gmt -collapse false -mode Max_probe -norm meandiv -nperm 1000 -rnk CW1.1_vs_GFP.rnk -scoring_scheme weighted -rpt_label CW1.1_vs_GFP -include_only_symbols true -make_sets true -plot_top_x 30 -rnd_seed timestamp -set_max 500 -set_min 15 -zip_report false -out gsea -gui false 2>CW1.1_vs_GFP_gsea.err &

java -cp /n/rinn_data1/user-supported/bin/gsea2-2.07.jar -Xmx5000m xtools.gsea.GseaPreranked -gmx gseaftp.broadinstitute.org://pub/gsea/gene_sets/c2.all.v3.0.symbols.gmt -collapse false -mode Max_probe -norm meandiv -nperm 1000 -rnk CW1.2_vs_GFP.rnk -scoring_scheme weighted -rpt_label CW1.2_vs_GFP -include_only_symbols true -make_sets true -plot_top_x 30 -rnd_seed timestamp -set_max 500 -set_min 15 -zip_report false -out gsea -gui false 2>CW1.2_vs_GFP_gsea.err &

java -cp /n/rinn_data1/user-supported/bin/gsea2-2.07.jar -Xmx5000m xtools.gsea.GseaPreranked -gmx gseaftp.broadinstitute.org://pub/gsea/gene_sets/c2.all.v3.0.symbols.gmt -collapse false -mode Max_probe -norm meandiv -nperm 1000 -rnk CW1.3_vs_GFP.rnk -scoring_scheme weighted -rpt_label CW1.3_vs_GFP -include_only_symbols true -make_sets true -plot_top_x 30 -rnd_seed timestamp -set_max 500 -set_min 15 -zip_report false -out gsea -gui false 2>CW1.3_vs_GFP_gsea.err &

java -cp /n/rinn_data1/user-supported/bin/gsea2-2.07.jar -Xmx5000m xtools.gsea.GseaPreranked -gmx gseaftp.broadinstitute.org://pub/gsea/gene_sets/c2.all.v3.0.symbols.gmt -collapse false -mode Max_probe -norm meandiv -nperm 1000 -rnk CW2.1_vs_GFP.rnk -scoring_scheme weighted -rpt_label CW2.1_vs_GFP -include_only_symbols true -make_sets true -plot_top_x 30 -rnd_seed timestamp -set_max 500 -set_min 15 -zip_report false -out gsea -gui false 2>CW2.1_vs_GFP_gsea.err &

java -cp /n/rinn_data1/user-supported/bin/gsea2-2.07.jar -Xmx5000m xtools.gsea.GseaPreranked -gmx gseaftp.broadinstitute.org://pub/gsea/gene_sets/c2.all.v3.0.symbols.gmt -collapse false -mode Max_probe -norm meandiv -nperm 1000 -rnk CW3.1_vs_GFP.rnk -scoring_scheme weighted -rpt_label CW3.1_vs_GFP -include_only_symbols true -make_sets true -plot_top_x 30 -rnd_seed timestamp -set_max 500 -set_min 15 -zip_report false -out gsea -gui false 2>CW3.1_vs_GFP_gsea.err &

java -cp /n/rinn_data1/user-supported/bin/gsea2-2.07.jar -Xmx5000m xtools.gsea.GseaPreranked -gmx gseaftp.broadinstitute.org://pub/gsea/gene_sets/c2.all.v3.0.symbols.gmt -collapse false -mode Max_probe -norm meandiv -nperm 1000 -rnk CW6.1_vs_GFP.rnk -scoring_scheme weighted -rpt_label CW6.1_vs_GFP -include_only_symbols true -make_sets true -plot_top_x 30 -rnd_seed timestamp -set_max 500 -set_min 15 -zip_report false -out gsea -gui false 2>CW6.1_vs_GFP_gsea.err &

java -cp /n/rinn_data1/user-supported/bin/gsea2-2.07.jar -Xmx5000m xtools.gsea.GseaPreranked -gmx gseaftp.broadinstitute.org://pub/gsea/gene_sets/c2.all.v3.0.symbols.gmt -collapse false -mode Max_probe -norm meandiv -nperm 1000 -rnk GFP_vs_pTrex.rnk -scoring_scheme weighted -rpt_label GFP_vs_pTrex -include_only_symbols true -make_sets true -plot_top_x 30 -rnd_seed timestamp -set_max 500 -set_min 15 -zip_report false -out gsea -gui false 2>GFP_vs_pTrex_gsea.err &

